dev_addr: 0.0.0.0:10000

site_name: Mkdocs-Template

nav:
    - Overview: index.md
    - Example-Service:
          Overview: Services/Example-Service/index.md
          example-get-endpoint: Services/Example-Service/Endpoints/example-get-endpoint.md
          example-post-endpoint: Services/Example-Service/Endpoints/example-post-endpoint.md
          example-put-endpoint: Services/Example-Service/Endpoints/example-put-endpoint.md
          example-delete-endpoint: Services/Example-Service/Endpoints/example-delete-endpoint.md

theme:
    name: material
    palette:
        scheme: slate
        primary: deep purple
    features:
        - content.code.copy
    language: en

plugins:
    - include-markdown:
          encoding: ascii
          preserve_includer_indent: false
          dedent: false
          trailing_newlines: true
          comments: true
          rewrite_relative_urls: true
          heading_offset: 0
          start: <!--start-->
          end: <!--end-->
          opening_tag: '{%'
          closing_tag: '%}'

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
    - stylesheets/extra.css
